[package]
name = "zentime-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "zentime"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
spin_sleep = "1.1.1"
